import type { LogStore, MessageRow, SessionRow } from "./store.js";

export interface DigestData {
  from: Date;
  to: Date;
  totalCalls: number;
  sessions: number;
  serverCounts: Record<string, number>;
  toolCounts: Record<string, number>;
  policyEvents: { blocks: number; pauseApproved: number; pauseDenied: number };
  newTools: string[];
}

export function buildDigestData(
  store: LogStore,
  from: Date,
  to: Date
): DigestData {
  const fromMs = from.getTime();
  const toMs = to.getTime();

  const sessions = store.getSessionsInRange(fromMs, toMs);
  const sessionMap = new Map<string, SessionRow>(sessions.map(s => [s.id, s]));
  const messages = store.getMessagesInRange(fromMs, toMs);
  const inbound = messages.filter(m => m.direction === "inbound");

  const serverCounts: Record<string, number> = {};
  for (const msg of inbound) {
    const session = sessionMap.get(msg.sessionId);
    const name = session?.serverName ?? "(unknown)";
    serverCounts[name] = (serverCounts[name] ?? 0) + 1;
  }

  const toolCounts: Record<string, number> = {};
  for (const msg of inbound) {
    if (msg.method.startsWith("(")) continue; // skip pseudo-methods
    toolCounts[msg.method] = (toolCounts[msg.method] ?? 0) + 1;
  }

  const policyEvents = store.getPolicyEventsInRange(fromMs, toMs);

  const knownBefore = store.getDistinctMethodsBefore(fromMs);
  const newTools = [...new Set(inbound.map(m => m.method))]
    .filter(m => !m.startsWith("(") && !knownBefore.has(m));

  return {
    from,
    to,
    totalCalls: inbound.length,
    sessions: sessions.length,
    serverCounts,
    toolCounts,
    policyEvents,
    newTools,
  };
}

function pad(n: number): string {
  return String(n).padStart(2, "0");
}

function fmtDate(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function top(counts: Record<string, number>, n = 10): Array<[string, number]> {
  return Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, n);
}

export function formatDigest(data: DigestData): string {
  const sep = "═".repeat(55);
  const thin = "─".repeat(55);
  const lines: string[] = [];

  lines.push(sep);
  lines.push(`SousMCP Weekly Digest · ${fmtDate(data.from)} – ${fmtDate(data.to)}`);
  lines.push(sep);
  lines.push("");

  // Overview
  lines.push("Overview");
  lines.push(thin);
  lines.push(`  ${data.totalCalls} tool calls across ${data.sessions} sessions`);
  lines.push("");

  // Servers
  const servers = top(data.serverCounts);
  if (servers.length > 0) {
    lines.push("Most Active Servers");
    lines.push(thin);
    for (const [name, count] of servers) {
      lines.push(`  ${name.padEnd(28)} ${count} calls`);
    }
    lines.push("");
  }

  // Tools
  const tools = top(data.toolCounts);
  if (tools.length > 0) {
    lines.push("Most Used Tools");
    lines.push(thin);
    for (const [tool, count] of tools) {
      lines.push(`  ${tool.padEnd(28)} ${count} times`);
    }
    lines.push("");
  }

  // Policy events
  const { blocks, pauseApproved, pauseDenied } = data.policyEvents;
  if (blocks + pauseApproved + pauseDenied > 0) {
    lines.push("Policy Events");
    lines.push(thin);
    if (blocks > 0) lines.push(`  ${blocks} blocked`);
    if (pauseApproved > 0) lines.push(`  ${pauseApproved} paused and approved`);
    if (pauseDenied > 0) lines.push(`  ${pauseDenied} paused and denied`);
    lines.push("");
  }

  // New tools
  if (data.newTools.length > 0) {
    lines.push("New This Week");
    lines.push(thin);
    for (const tool of data.newTools) lines.push(`  ${tool}`);
    lines.push("");
  }

  if (data.totalCalls === 0) {
    lines.push("  (no activity this period)");
    lines.push("");
  }

  lines.push(sep);
  lines.push(`Generated by SousMCP on ${new Date().toISOString()}`);
  lines.push(`Run 'sousmcp log' to see the full message log.`);
  lines.push(sep);

  return lines.join("\n") + "\n";
}
